# See config.example.yml for documentation.
name: oot-gc
object: orig/PZLP01/sys/main.dol
hash: 8c5c365ae2df34c4cb27e86eb1cf30f2a2e4cd1b
symbols: config/PZLP01/symbols.txt
splits: config/PZLP01/splits.txt
mw_comment_version: 8

extract:
- symbol: gTgPcTPL
  header: gTgPcTPL.inc
