# See config.example.yml for documentation.
name: oot-gc
object: orig/PZLE01/sys/main.dol
hash: aed1c15af4d667a3cffd8621a6bb3fd08b4c3b04
symbols: config/PZLE01/symbols.txt
splits: config/PZLE01/splits.txt
mw_comment_version: 8

extract:
- symbol: gTgPcTPL
  header: gTgPcTPL.inc
